version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: 35.247.9.186
            port: 
            database: learning-graphql-1:us-west1:prismaserver
            schema: public
            user: postgres
            password: towamnb321123
            migrations: false
            ssl: false
